=== json-schema-org/community/programs/contractors/contractors-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "description": "Array of contractor profiles",
  "items": {
    "type": "object",
    "description": "Contractor profile",
    "properties": {
      "name": {
        "type": "string",
        "description": "Full name of the contractor"
      },
      "bio": {
        "type": "string",
        "description": "Biography of the contractor"
      },
      "email": {
        "type": "string",
        "format": "email",
        "description": "E-mail address of the contractor"
      },
      "website": {
        "type": "string",
        "format": "url",
        "description": "Website URL of the contractor"
      },
      "github": {
        "type": "string",
        "description": "GitHub profile URL of the contractor"
      },
      "x": {
        "type": "string",
        "description": "X profile URL of the contractor"
      },
      "mastodon": {
        "type": "string",
        "description": "Mastodon profile URL of the contractor"
      },
      "linkedin": {
        "type": "string",
        "description": "LinkedIn profile URL of the contractor"
      },
      "incorporatedIn": {
        "type": "array",
        "description": "Countries where the contractor is incorporated",
        "items": {
          "type": "string"
        }
      },
      "type": {
        "enum": [ "tsc", "ambassor" ],
        "description": "Status of the contractor in the JSON Schema organization"
      },
      "links": {
        "type": "array",
        "description": "List of key links to showcase",
        "items": {
          "type": "object",
          "description": "Details of a specific link",
          "properties": {
            "title": {
              "type": "string",
              "description": "Title of the link"
            },
            "url": {
              "type": "string",
              "format": "uri",
              "description": "The link URL"
            }
          },
          "required": ["title", "url"]
        }
      }
    },
    "required": ["name", "bio", "type", "github", "incorporatedIn", "links"]
  }
}

=== json-schema-org/community/programs/contractors/contractors.json
[
  {
    "name": "Juan Cruz Viotti",
    "github": "jviotti",
    "linkedin": "jviotti",
    "email": "jv@jviotti.com",
    "website": "https://www.jviotti.com",
    "type": "tsc",
    "incorporatedIn": [ "UK" ],
    "bio": "I'm a TSC member of JSON Schema, did award-winning research at the University of Oxford in the space of binary serialization and compression using JSON Schema, co-authored an O'Reilly book covering JSON Schema, and own several projects in the ecosystem, ranging educational material like LearnJSONSchema.com to a high-performance C++ JSON Schema compiler and validator. I have experience helping organizations be successful with JSON Schema in the Data, API, and IoT spaces all the way from architecture, ontology design, and XML migrations to training and custom development. I'm eager to help you take your JSON Schema integrations to the next level!",
    "links": [
      {
        "title": "O'Reilly Book: Unifying Business, Data, and Code: Designing Data Products with JSON Schema",
        "url": "https://learning.oreilly.com/library/view/unifying-business-data/9781098144999/"
      },
      {
        "title": "JSON Schema CLI: The CLI for working with JSON Schema. Covers formatting, linting, testing, bundling, and more for both local development and CI/CD pipelines",
        "url": "https://github.com/intelligence-ai/jsonschema"
      },
      {
        "title": "JSON BinPack: binary serialization with JSON Schema, more space-efficient than Protocol Buffers and similar alternatives (work in progress)",
        "url": "https://jsonbinpack.sourcemeta.com"
      },
      {
        "title": "AlterSchema: Automatic upgrades between versions of JSON Schema (downgrades coming soon)",
        "url": "https://alterschema.sourcemeta.com"
      },
      {
        "title": "Blaze: the ultra high-performance JSON Schema validator, providing validation in the nano-second range, along with perfect compliance scores. Supports Draft 4, Draft 6, Draft 7, 2019-09 and 2020-12",
        "url": "https://github.com/sourcemeta/blaze"
      },
      {
        "title": "Blog post: A deep dive on lexical and dynamic scopes, essential for understanding more advanced topics like dynamic referencing",
        "url": "https://json-schema.org/blog/posts/understanding-lexical-dynamic-scopes"
      }
    ]
  },
  {
    "name": "Julian Berman",
    "github": "Julian",
    "linkedin": "julian-berman",
    "email": "Julian+JSON.Schema@GrayVines.com",
    "type": "tsc",
    "incorporatedIn": [],
    "bio": "Julian is an experienced engineering leader, JSON Schema TSC member and a member of the JSON Schema core team for over 10 years. He founded the JSON Schema Test Suite and Bowtie projects, helping countless implementers (and users) of all JSON Schema implementations ensure compliance with the specification. He also wrote and maintains the most widely used Python implementation of JSON Schema, along with a large number of projects in its orbit, and is a long-time contributor to the wider open source Python ecosystem. He has deep experience running engineering teams (in previous lives in the context of machine learning for large-enterprise consumer experience marketing). He also is a lecturer at Columbia University, who cares deeply about ensuring technology is accessible and easy to understand for all. Let him help your organization get smarter about how you use JSON Schema, how you collaborate with it across teams, and how you effectively build reliable production systems which leverage JSON Schema.",
    "links": [
      {
        "title": "python-jsonschema, the most widely used Python implementation of JSON Schema for over 10 years",
        "url": "https://github.com/python-jsonschema/jsonschema/"
      },
      {
        "title": "Bowtie, a meta-validator for using JSON Schema implementations across every programming language in the world",
        "url": "https://bowtie.report"
      },
      {
        "title": "The official JSON Schema Test Suite, a large collection of compliance tests for the JSON Schema specification used by many or most implementations of JSON Schema",
        "url": "https://github.com/json-schema-org/JSON-Schema-Test-Suite"
      }
    ]
  },
  {
    "name": "Jason Desrosiers",
    "github": "jdesrosiers",
    "linkedin": "jason-desrosiers",
    "email": "jason@hyperjump.io",
    "type": "tsc",
    "incorporatedIn": ["California, USA"],
    "bio": "Jason is a recognized expert and active contributor to the JSON Schema community with over a decade of experience. As a member of the Technical Steering Committee (TSC), he has helped shape the specification and establish best practices. In addition, Jason has developed innovative techniques for writing complex schemas that are scalable, maintainable, efficient, and produce error messages that are clear and helpful.<br><br>As the author and maintainer of the `@hyperjump/json-schema` validator, Jason has created an implementation that is widely regarded as a trusted reference for understanding and verifying correct behavior in complex scenarios.<br><br>Jason is also highly knowledgeable in using JSON Schema and JSON Hyper-Schema to design APIs that are easy to use, well-documented, and adaptable over time. He helps teams build APIs that not only meet immediate needs but also ensure smooth evolution as business requirements change, making it easier to maintain and scale them as the organization grows.<br><br>In addition to his JSON Schema expertise, Jason holds a Master's degree in Software Engineering and brings extensive experience in Pair/Mob Programming, Test-Driven Development, and coaching teams to improve their coding skills and productivity. He specializes in hands-on collaboration, working alongside teams to teach practical skills in the context of their real-world projects.<br><br>If you need expert guidance on JSON Schema, API design, schema development, or improving your teamâ€™s development practices, reach out to Jason to discuss your needs.",
    "links": [
      {
        "title": "@hyperjump/json-schema -- A JSON Schema implementation with support for every validation, annotations, bundling, and more in every JSON Schema dialect since draft-04.",
        "url": "https://github.com/hyperjump-io/json-schema"
      },
      {
        "title": "Blog post -- Validating OpenAPI and JSON Schema",
        "url": "https://json-schema.org/blog/posts/validating-openapi-and-json-schema"
      },
      {
        "title": "Blog post -- Towards a stable JSON Schema",
        "url": "https://json-schema.org/blog/posts/future-of-json-schema"
      },
      {
        "title": "API Specifications Conference 2021 - Maintaining JSON Schemas at Scale",
        "url": "https://www.youtube.com/watch?v=GjJpRsVffg0"
      }
    ]
  }
]
